const sequelize = require('../config/connection');
const { Post } = require('../models');

const postdata = [
  {
    title: "Test Post Numero Uno",
    content: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Risus nec feugiat in fermentum posuere urna nec. Mattis molestie a iaculis at erat pellentesque adipiscing commodo. Ut tortor pretium viverra suspendisse potenti nullam ac tortor. Donec pretium vulputate sapien nec sagittis aliquam malesuada bibendum. Et sollicitudin ac orci phasellus egestas. Ac turpis egestas maecenas pharetra convallis posuere. Nisi porta lorem mollis aliquam. Augue eget arcu dictum varius duis at consectetur. Varius vel pharetra vel turpis nunc. Curabitur vitae nunc sed velit.

    Tellus at urna condimentum mattis pellentesque id nibh tortor. Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh sit. Amet consectetur adipiscing elit ut. Bibendum enim facilisis gravida neque convallis a. Dolor purus non enim praesent elementum. Fusce id velit ut tortor pretium viverra suspendisse. Vitae auctor eu augue ut lectus arcu. Laoreet non curabitur gravida arcu ac tortor dignissim convallis. Ullamcorper a lacus vestibulum sed arcu non odio euismod. Aliquam etiam erat velit scelerisque in dictum non consectetur. Malesuada pellentesque elit eget gravida cum sociis natoque penatibus. Et leo duis ut diam quam. Felis donec et odio pellentesque diam volutpat commodo sed. Gravida arcu ac tortor dignissim convallis aenean et. Leo duis ut diam quam. Nec ultrices dui sapien eget mi. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget egestas.
    
    Sit amet mauris commodo quis imperdiet. Ornare massa eget egestas purus viverra accumsan in. Integer vitae justo eget magna fermentum iaculis eu. Sit amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus. Pulvinar elementum integer enim neque volutpat. Bibendum enim facilisis gravida neque convallis a cras semper auctor. Duis ut diam quam nulla porttitor massa id. Quam adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Tellus in metus vulputate eu. Cras tincidunt lobortis feugiat vivamus at augue eget arcu. Risus nullam eget felis eget nunc. Habitant morbi tristique senectus et netus et malesuada fames ac.
    
    Massa enim nec dui nunc. Tincidunt tortor aliquam nulla facilisi cras fermentum odio eu feugiat. Suspendisse ultrices gravida dictum fusce ut placerat orci. Sed id semper risus in hendrerit gravida rutrum quisque non. Venenatis a condimentum vitae sapien pellentesque. Congue quisque egestas diam in arcu. Porttitor leo a diam sollicitudin tempor id eu. Est velit egestas dui id ornare arcu. Risus viverra adipiscing at in tellus integer feugiat scelerisque. Et malesuada fames ac turpis egestas integer. Fusce id velit ut tortor pretium viverra suspendisse. Elementum eu facilisis sed odio morbi. Molestie a iaculis at erat. Mi sit amet mauris commodo quis imperdiet. Arcu cursus euismod quis viverra nibh cras pulvinar mattis nunc. Neque laoreet suspendisse interdum consectetur libero id faucibus. Eros in cursus turpis massa tincidunt dui. Scelerisque eleifend donec pretium vulputate sapien nec sagittis. Mattis vulputate enim nulla aliquet porttitor lacus.
    
    Tellus rutrum tellus pellentesque eu tincidunt. Pharetra sit amet aliquam id diam maecenas ultricies mi. Posuere lorem ipsum dolor sit amet consectetur. Ultrices gravida dictum fusce ut placerat orci nulla. Est ante in nibh mauris cursus. A cras semper auctor neque. Ac odio tempor orci dapibus ultrices in. Ornare lectus sit amet est placerat. Nisl condimentum id venenatis a condimentum vitae sapien. Fames ac turpis egestas sed. Nulla facilisi etiam dignissim diam quis. Erat pellentesque adipiscing commodo elit at imperdiet. Viverra vitae congue eu consequat ac felis donec et odio. Bibendum est ultricies integer quis auctor elit sed vulputate. Faucibus et molestie ac feugiat. Ultricies tristique nulla aliquet enim tortor at auctor.`,
    user_id: 1,
  
  }
];